### ISSUE TITLE
[VaultMP] Init stage behavior change

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [foxtacles/vaultmp#148]
I think it'd be better to let the vaultmp app to be able to open its window and show the server list. We will check for F3 and other dlls presence only after user hit the connect button (maybe he just want to see the currently available servers)

**Comment by gravypod** [comment]
Hello. I don't know if this is the right place to ask this but are you ( @Sh1ft0x0EF  ) and @Koncord going to finish this project? Do you have a list of things that need to be done? Do you have a simple way to get the IDE set up for this?

**Comment by Sh1ft0x0EF** [comment]
@gravypod, greetings
I'm not sure about @Koncord, cause he's currently working on another project
It's hard to say about finishing the project from this point - it's still lotta work to do
You can visit the [milestone page](https://github.com/foxtacles/vaultmp/milestones)
I've almost finished the CMake support. You would be able to generate the VS projects with it if you need

**Comment by CaesarNVMP** [comment]
I'm interested in forming together an official development team with you shift/other developers to help complete vaultmp, I found vaultmp more stable than NVMP and i think Vaultmp has the potential, While i don't have coding experience myself I am great at admin/managing and good in the new vegas geck, and every team needs someone to help keep things together and do all the multimedia which is where i'll likely come in.

If you are interested we can talk in the discord i've set up called VaultMP Reborn especially for you guys. 

https://discord.gg/DmZ8P8Z

I think if i could suggest something based on knowledge i do have, sometimes due to the multiplayer framework the game hits it's memory cap, so i think making the vaultmp boot off the 4gb patched falloutnv.exe by roybatty would be most ideal for stability and a non-crash experience, + It also automatically loads in NVSE meaning you do not need to worry about nvse_loader.exe if playing singleplayer,

**Comment by Sh1ft0x0EF** [comment]
First try
It doesn't try search for game dlls now until user hit the "Join" button
But it currently doesn't open any window...

**Comment by Sh1ft0x0EF** [comment]
I think it's mostly done
Probably should revisit it later
Accessible here for now:
https://github.com/VaultTecWorkshop/vaultmp-vtw/tree/reborn-dev
